import json
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)  # Enable CORS for development

board = ['GO', 
        'HERO_SLOT', 'ITEM_SLOT', 'ITEM_SLOT', 'ITEM_SLOT', 'PAD', 'PAD','PAD', 'PAD', 'PAD', 'PAD', 'PAD','PAD','PAD','PAD','PAD','PAD',
        'PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD',
        'PAD','PAD','PAD','PAD','PAD',
        'HERO_BOUNDARY',
        'PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD','PAD',
        'BENCH_BOUNDARY',
        'PAD','PAD','PAD','PAD','PAD',
        'SHOP_BOUNDARY',
        'ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT',
        'ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT','ITEM_SLOT',
        'ITEM_BOUNDARY',
        'PAD','PAD','PAD',
        'AUGMENT_BOUNDARY',
        'CAN_REROLL',
        'MASK',
        'PAD','PAD','PAD','PAD',
        'EOS']
hero_boundary = 45
bench_boundary= 56
shop_boundary= 62
item_boundary= 78
augment_boundary= 82
reroll= 83
decision= 84

unit_dict = {
 "TFT14_Alistar":'Alistar',
 "TFT14_DrMundo": 'Dr. Mundo',
 "TFT14_Jax":'Jax',
 "TFT14_Kindred":'Kindred',
 "TFT14_KogMaw":"Kog'Maw",
 "TFT14_Morgana": 'Morgana',
 "TFT14_NidaleeCougar":'Nidalee',
 "TFT14_Poppy":'Poppy',
 "TFT14_Seraphine":'Seraphine',
 "TFT14_Shaco": 'Shaco',
 "TFT14_Sylas":'Sylas',
 "TFT14_Vi":'Vi',
 "TFT14_Zyra":'Zyra',
 "TFT14_Darius": 'Darius',
 "TFT14_Ekko":'Ekko',
 "TFT14_Graves":'Graves',
 "TFT14_Illaoi":'Illaoi',
 "TFT14_Jhin":'Jhin',
 "TFT14_LeBlanc": 'LeBlanc',
 "TFT14_Naafiri":'Naafiri',
 "TFT14_Rhaast":'Rhaast',
 "TFT14_Shyvana":'Shyvana',
 "TFT14_Skarner":'Skarner',
 "TFT14_TwistedFate":'Twisted Fate',
 "TFT14_Vayne":'Vayne',
 "TFT14_Veigar":'Veigar',
 "TFT14_Braum":'Braum',
 "TFT14_Draven":'Draven',
 "TFT14_Elise": 'Elise',
 "TFT14_Fiddlesticks": 'Fiddlesticks',
 "TFT14_Galio":'Galio',
 "TFT14_Gragas":'Gragas',
 "TFT14_Jarvan":'Jarvan IV',
 "TFT14_Jinx":'Jinx',
 "TFT14_Mordekaiser":'Mordekaiser',
 "TFT14_Rengar":'Rengar',
 "TFT14_Senna":'Senna',
 "TFT14_Varus":'Varus',
 "TFT14_Yuumi":'Yuumi',
 "TFT14_Annie":'Annie',
 "TFT14_Aphelios":'Aphelios',
 "TFT14_Brand":'Brand',
 "TFT14_Chogath":"Cho'Gath",
 "TFT14_Leona":'Leona',
 "TFT14_MissFortune": 'Miss Fortune',
 "TFT14_Neeko":'Neeko',
 "TFT14_Sejuani":'Sejuani',
 "TFT14_Vex":'Vex',
 "TFT14_Xayah":'Xayah',
 "TFT14_Zed":'Zed',
 "TFT14_Zeri":'Zeri',
 "TFT14_Ziggs":'Ziggs',
 "TFT14_Aurora":'Aurora',
 "TFT14_Garen": 'Garen',
 "TFT14_Kobuko":'Kobuko',
 "TFT14_Renekton":'Renekton',
 "TFT14_Samira":'Samira',
 "TFT14_Urgot":'Urgot',
 "TFT14_Viego":'Viego',
 "TFT14_Zac":'Zac',
 "TFT_ArmoryKeyComponent": 'PAD',
 'TFT_ArmoryKeyCompleted': 'PAD'

}

item_dict = {
 "TFT_Item_AdaptiveHelm": 'Adaptive Helm',
 "TFT_Item_ArchangelsStaff":"Archangel's Staff",
 "TFT_Item_Bloodthirster":'Bloodthirster',
 "TFT_Item_BlueBuff": 'Blue Buff',
 "TFT_Item_BrambleVest":'Bramble Vest',
 "TFT_Item_Crownguard":'Crownguard',
 "TFT_Item_Deathblade":'Deathblade',
 "TFT_Item_DragonsClaw":"Dragon's Claw",
 "TFT_Item_GuardianAngel":'Edge of Night',
 "TFT_Item_SpectralGauntlet":'Evenshroud',
 "TFT_Item_GargoyleStoneplate":'Gargoyle Stoneplate',
 "TFT_Item_MadredsBloodrazor":'Giant Slayer',
 "TFT_Item_PowerGauntlet":'Guardbreaker',
 "TFT_Item_GuinsoosRageblade":"Guinsoo's Rageblade",
 "TFT_Item_UnstableConcoction":'Hand Of Justice',
 "TFT_Item_HextechGunblade": 'Hextech Gunblade',
 "TFT_Item_InfinityEdge":'Infinity Edge',
 "TFT_Item_IonicSpark":'Ionic Spark',
 "TFT_Item_JeweledGauntlet":'Jeweled Gauntlet',
 "TFT_Item_LastWhisper":'Last Whisper',
 "TFT_Item_Morellonomicon":'Morellonomicon',
 "TFT_Item_Leviathan":"Nashor's Tooth",
 "TFT_Item_FrozenHeart":"Protector's Vow",
 "TFT_Item_Quicksilver":'Quicksilver',
 "TFT_Item_RabadonsDeathcap":"Rabadon's Deathcap",
 "TFT_Item_RapidFireCannon":'Red Buff',
 "TFT_Item_Redemption":'Redemption',
 "TFT_Item_RunaansHurricane":"Runaan's Hurricane",
 "TFT_Item_SpearOfShojin":'Spear of Shojin',
 "TFT_Item_StatikkShiv": 'Statikk Shiv',
 "TFT_Item_NightHarvester": 'Steadfast Heart',
 "TFT_Item_SteraksGage":"Sterak's Gage",
 "TFT_Item_RedBuff":'Sunfire Cape',
 "TFT_Item_TacticiansRing": "Tactician's Cape",
 "TFT_Item_ForceOfNature":"Tactician's Crown",
 "TFT_Item_TacticiansScepter": "Tactician's Shield",
 "TFT_Item_ThiefsGloves":"Thief's Gloves",
 "TFT_Item_TitansResolve":"Titan's Resolve",
 "TFT_Item_WarmogsArmor":"Warmog's Armor",
 "TFT14_Item_DarkWebEmblemItem": 'Anima Squad Emblem',
 "TFT14_Item_ArmorcladEmblemItem":'Bastion Emblem',
 'Item_Icons/Traits/Spatula/Set14/TFT14_Emblem_BoomBots.TFT_Set14':'BoomBot Emblem',
 "TFT14_Item_BruiserEmblemItem":'Bruiser Emblem',
 "TFT14_Item_DivinicorpEmblemItem":'Divinicorp Emblem',
 "TFT14_Item_ThirstyEmblemItem":'Dynamo Emblem',
 "TFT14_Item_CutterEmblemItem":'Executioner Emblem',
 "TFT14_Item_EdgeRunnerEmblemItem":'Exotech Emblem',
 "TFT14_Item_ImmortalEmblemItem":'Golden Ox Emblem',
 "TFT14_Item_MarksmanEmblemItem":'Marksman Emblem',
 "TFT14_Item_SwiftEmblemItem":'Rapidfire Emblem',
 "TFT14_Item_StrongEmblemItem":'Slayer Emblem',
 "TFT14_Item_ControllerEmblemItem":'Strategist Emblem',
 "TFT14_Item_StreetDemonEmblemItem":'Street Demon Emblem',
 "TFT14_Item_MobEmblemItem":'Syndicate Emblem',
 "TFT14_Item_TechieEmblemItem":'Techie Emblem',
 "TFT14_Item_GuardianEmblemItem":'Vanguard Emblem',
 "TFT5_Item_RedemptionRadiant":'Absolution',
 "TFT5_Item_BloodthirsterRadiant":'Blessed Bloodthirster',
 "TFT5_Item_BlueBuffRadiant":'Blue Blessing',
 "TFT5_Item_GuardianAngelRadiant": 'Brink of Dawn',
 "TFT5_Item_FrozenHeartRadiant":"Bulwark's Oath",
 "TFT5_Item_IonicSparkRadiant":'Covalent Spark',
 "TFT5_Item_RapidFirecannonRadiant":'Crest of Cinders',
 "TFT5_Item_GiantSlayerRadiant":'Demonslayer',
 "TFT5_Item_DragonsClawRadiant":"Dragon's Will",
 "TFT5_Item_GargoyleStoneplateRadiant":'Dvarapala Stoneplate',
 "TFT5_Item_SpectralGauntletRadiant":'Equinox',
 "TFT5_Item_LastWhisperRadiant":'Eternal Whisper',
 "TFT5_Item_HandOfJusticeRadiant":'Fist of Fairness',
 "TFT5_Item_JeweledGauntletRadiant":'Glamorous Gauntlet',
 "TFT5_Item_GuinsoosRagebladeRadiant":"Guinsoo's Reckoning",
 "TFT5_Item_HextechGunbladeRadiant":'Hextech Lifeblade',
 "TFT5_Item_AdaptiveHelmRadiant":"Jak'sho the Protean",
 "TFT5_Item_NightHarvesterRadiant":'Legacy of the Colossus',
 "TFT5_Item_DeathbladeRadiant":'Luminous Deathblade',
 "TFT5_Item_MorellonomiconRadiant":'More More-ellonomicon',
 "TFT5_Item_QuicksilverRadiant":'Quickestsilver',
 "TFT5_Item_RabadonsDeathcapRadiant":"Rabadon's Ascended Deathcap",
 "TFT5_Item_ThiefsGlovesRadiant":"Rascal's Gloves",
 "TFT5_Item_BrambleVestRadiant":'Rosethorn Vest',
 "TFT5_Item_CrownguardRadiant":'Royal Crownshield',
 "TFT5_Item_RunaansHurricaneRadiant":"Runaan's Tempest",
 "TFT5_Item_SpearOfShojinRadiant":'Spear of Hirana',
 "TFT5_Item_StatikkShivRadiant": "Statikk's Favor",
 "TFT5_Item_SteraksGageRadiant": "Sterak's Megashield",
 "TFT5_Item_SunfireCapeRadiant":'Sunlight Cape',
 "TFT5_Item_LeviathanRadiant":"The Baron's Gift",
 "TFT5_Item_TitansResolveRadiant":"Titan's Vow",
 "TFT5_Item_ArchangelsStaffRadiant":"Urf-Angel's Staff",
 "TFT5_Item_WarmogsArmorRadiant":"Warmog's Pride",
 "TFT5_Item_TrapClawRadiant":'Willbreaker',
 "TFT5_Item_InfinityEdgeRadiant":'Zenith Edge',
 "TFT4_Item_OrnnAnimaVisage":'Anima Visage',
 "TFT9_Item_OrnnPrototypeForge":"Blacksmith's Gloves",
 "TFT_Item_Artifact_BlightingJewel":'Blighting Jewel',
 "TFT4_Item_OrnnDeathsDefiance":"Death's Defiance",
 "TFT9_Item_OrnnDeathfireGrasp":'Deathfire Grasp',
 "TFT_Item_Artifact_Fishbones":'Fishbones',
 "TFT7_Item_ShimmerscaleGamblersBlade":"Gambler's Blade",
 "TFT4_Item_OrnnTheCollector":'Gold Collector',
 "TFT_Item_Artifact_HorizonFocus":'Horizon Focus',
 "TFT9_Item_OrnnHullbreaker":'Hullcrusher',
 "TFT4_Item_OrnnInfinityForce":'Infinity Force',
 "TFT_Item_Artifact_InnervatingLocket":'Innervating Locket',
 "TFT_Item_Artifact_LichBane":'Lich Bane',
 "TFT_Item_Artifact_LightshieldCrest":'Lightshield Crest',
 "TFT_Item_Artifact_LudensTempest":"Luden's Tempest",
 "TFT4_Item_OrnnMuramana":'Manazane',
 "TFT_Item_Artifact_Mittens":'Mittens',
 "TFT7_Item_ShimmerscaleMogulsMail":"Mogul's Mail",
 "TFT_Item_Artifact_ProwlersClaw": "Prowler's Claw",
 "TFT_Item_Artifact_RapidFirecannon":'Rapid Firecannon',
 "TFT_Item_Artifact_SeekersArmguard":"Seeker's Armguard",
 "TFT_Item_Artifact_SilvermereDawn":'Silvermere Dawn',
 "TFT9_Item_OrnnHorizonFocus":"Sniper's Focus",
 "TFT_Item_Artifact_SpectralCutlass":'Spectral Cutlass',
 "TFT_Item_Artifact_SuspiciousTrenchCoat":'Suspicious Trench Coat',
 "TFT_Item_Artifact_TalismanOfAscension":'Talisman Of Ascension',
 "TFT9_Item_OrnnTrickstersGlass":"Trickster's Glass",
 "TFT_Item_Artifact_UnendingDespair":'Unending Despair',
 "TFT_Item_Artifact_WitsEnd":"Wit's End",
 "TFT4_Item_OrnnZhonyasParadox":"Zhonya's Paradox",
 "TFT11_Item_ThiefsGlovesSupport":"Accomplice's Gloves",
 "TFT_Item_AegisOfTheLegion":'Aegis of the Legion',
 "TFT_Item_BansheesVeil":"Banshee's Veil",
 "TFT_Item_Chalice":'Chalice of Power',
 "TFT_Item_SupportKnightsVow": "Knight's Vow",
 "TFT_Item_LocketOfTheIronSolari":'Locket of the Iron Solari',
 "TFT_Item_Moonstone":'Moonstone Renewer',
 "TFT7_Item_ShimmerscaleHeartOfGold":'Needlessly Big Gem',
 "TFT4_Item_OrnnObsidianCleaver": 'Obsidian Cleaver',
 "TFT4_Item_OrnnRanduinsSanctum":"Randuin's Omen",
 "TFT_Item_Shroud":'Shroud of Stillness',
 "TFT_Item_Spite":'Spite',
 "TFT_Item_EternalFlame":'The Eternal Flame',
 "TFT_Item_UnstableTreasureChest":'Unstable Treasure Chest',
 "TFT_Item_RadiantVirtue":'Virtue of the Martyr',
 "TFT_Item_ZekesHerald":"Zeke's Herald",
 "TFT_Item_Zephyr":'Zephyr',
 "TFT5_Item_ZzRotPortalRadiant": "Zz'Rot Portal",
 "TFT_Item_BFSword":"B.F. Sword",
 "TFT_Item_RecurveBow":"Recurve Bow",
 "TFT_Item_NeedlesslyLargeRod":"Needlessly Large Rod",
 "TFT_Item_TearOfTheGoddess":"Tear of the Goddess",
 "TFT_Item_ChainVest":"Chain Vest",
 "TFT_Item_NegatronCloak":"Negatron Cloak",
 "TFT_Item_GiantsBelt":"Giant's Belt",
 "TFT_Item_SparringGloves":"Sparring Gloves",
 "TFT_Item_FryingPan":"Frying Pan",
 "TFT_Item_Spatula":"Spatula",
 "": "ITEM_SLOT"
}

augment_dict = {
 "TFT7_Augment_AFK":'AFK',
 "TFT14_Augment_JaxCarry":'Adaptive Strikes',
 "TFT_Augment_Backup":'Backup',
 "TFT7_Augment_BandOfThieves1":'Band of Thieves I',
 "TFT7_Augment_BigFriend":'Big Friend I',
 "TFT9_Augment_RedBuff":'Blistering Strikes',
 "TFT_Augment_BranchingOut":'Branching Out',
 "TFT_Augment_BranchingOutPlus":'Branching Out+',
 "TFT_Augment_BulkyBuddies1":'Bulky Buddies I',
 "TFT14_Augment_PoppyCarry":'Button Mash',
 "TFT_Augment_CalledShot":'Called Shot',
 "TFT9_Augment_BardPlaybook1":"Caretaker's Ally",
 "TFT14_Augment_ViCarry":'Cease and Desist',
 "TFT_Augment_ClimbTheLadder1":'Climb The Ladder I',
 "TFT9_Augment_CustomerIsAlwaysRight":'Component Buffet',
 "TFT_Augment_Corrosion":'Corrosion',
 "TFT_Augment_CraftedCrafting":'Crafted Crafting',
 "TFT_Augment_HeadStart":'Delayed Start',
 "TFT_Augment_DiversifiedPortfolio1":'Diversified Portfolio',
 "TFT_Augment_DiversifiedPortfolio2":'Diversified Portfolio+',
 "TFT_Augment_Dummify":'Dummify',
 "TFT_Augment_EyeForAnEye":'Eye For An Eye',
 "TFT_Augment_EyeForAnEyePlus":'Eye For An Eye+',
 "TFT_Augment_FindYourCenter":'Find Your Center',
 "TFT_Augment_FiresalePlus":'Firesale',
 "TFT_Augment_GlassCannonI":'Glass Cannon I',
 "TFT10_Augment_GoodForSomethingSilver":'Good For Something I',
 "TFT9_Augment_HealingOrbsI":'Healing Orbs I',
 "TFT_Augment_WealthyRehab1":'Health is Wealth I',
 "TFT9_Augment_IronAssets":'Iron Assets',
 "TFT_Augment_ItemCollector1":'Item Collector I',
 "TFT6_Augment_ItemGrabBag1":'Item Grab Bag I',
 "TFT_Augment_Kingslayer":'Kingslayer',
 "TFT7_Augment_LategameSpecialist":'Lategame Specialist',
 "TFT9_Augment_LongTimeCrafting":'Latent Forge',
 "TFT_Augment_Lineup":'Lineup',
 "TFT11_Augment_BloodBank":'Lunch Money',
 "TFT_Augment_Manaflow1":'Manaflow I',
 "TFT_Augment_Mentorship1":'Mentorship I',
 "TFT9_Augment_MissedConnections":'Missed Connections',
 "TFT_Augment_AllForOneI":'One For All I',
 "TFT6_Augment_OneTwoFive":'One, Two, Five!',
 "TFT9_Augment_OneTwosThree":'Ones Twos Three',
 "TFT11_Augment_OverEncumbered":'Over Encumbered',
 "TFT7_Augment_PandorasBench":"Pandora's Bench",
 "TFT6_Augment_PandorasItems":"Pandora's Items",
 "TFT_Augment_PatienceIsAVirtue":'Patience is a Virtue',
 "TFT_Augment_Placebo":'Placebo',
 "TFT_Augment_PlaceboPlus":'Placebo+',
 "TFT7_Augment_Preparation":'Preparation I',
 "TFT9_Augment_PumpingUp":'Pumping Up I',
 "TFT6_Augment_Recombobulator":'Recombobulator',
 "TFT_Augment_RestartMission":'Restart Mission',
 "TFT_Augment_RiggedShopPlus":'Rigged Shop+',
 "TFT9_Augment_RiskyMoves":'Risky Moves',
 "TFT9_Augment_Commander_RollingForDays":'Rolling For Days I',
 "TFT9_Augment_SilverSpoon":'Silver Spoon',
 "TFT9_Augment_DravenSpoilsOfWar":'Spoils of War I',
 "TFT6_Augment_Diversify1":'Stand United I',
 "TFT_Augment_SupportMining":'Support Mining',
 "TFT_Augment_SupportMiningPlus":'Support Mining+',
 "TFT_Augment_Survivor":'Survivor',
 "TFT_Augment_TableScraps":'Table Scraps',
 "TFT9_Augment_ArmyBuilding":'Team Building',
 "TFT9_Augment_Commander_TeamingUp1":'Teaming Up I',
 "TFT_Augment_TitanicTitan":'Titanic Titan',
 "TFT14_Augment_SylasCarry":'Wolf Unchained',
 "TFT9_Augment_YoungAndWildAndFree":'Young and Wild and Free',
 "TFT14_Augment_Controller_Vertical":'10,000 IQ',
 "TFT_Augment_MagicRoll": 'A Magic Roll',
 "TFT9_Augment_AllThatShimmers":'All That Shimmers',
 "TFT_Augment_AllThatShimmersPlus":'All That Shimmers+',
 "TFT14_Augment_RhaastCarry":'Alter Ego',
 "TFT14_Augment_AnimaSquadCrest": 'Anima Squad Crest',
 "TFT9_Augment_Commander_Ascension":'Ascension',
 "TFT_Augment_BRB":'BRB',
 "TFT_Augment_BadLuckProtection": 'Bad Luck Protection',
 "TFT14_Augment_ArmorcladCrest": 'Bastion Crest',
 "TFT7_Augment_BigFriend2":'Big Friend II',
 "TFT9_Augment_BigGrabBag":'Big Grab Bag',
 "TFT_Augment_BlazingSoul":'Blazing Soul I',
 "TFT14_Augment_Divinicorp_Splash":'Board of Directors',
 "TFT14_Augment_BoomBotsCrest":'BoomBot Crest',
 "TFT_Augment_BronzeForLifeI":'Bronze For Life I',
 "TFT14_Augment_BruiserCrest":'Bruiser Crest',
 "TFT_Augment_BulkyBuddies2":'Bulky Buddies II',
 "TFT6_Augment_CalculatedLoss":'Calculated Loss',
 "TFT14_Augment_Techie_Splash":'Capacitor',
 "TFT9_Augment_BardPlaybook2":"Caretaker's Favor",
 "TFT_Augment_CategoryFive":'Category Five',
 "TFT6_Augment_ClearMind": 'Clear Mind',
 "TFT_Augment_ClimbTheLadder2":'Climb The Ladder II',
 "TFT_Augment_ClockworkAccelerator":'Clockwork Accelerator',
 "TFT_Augment_CloningFacility": 'Cloning Facility',
 "TFT7_Augment_ClutteredMind":'Cluttered Mind',
 "TFT14_Augment_Techie_Vertical":'Cognitive Implant',
 "TFT_Augment_CookingPot":'Cooking Pot',
 "TFT14_Augment_Cyberboss_Cower":'Cower, Weaklings!',
 "TFT10_Augment_CrownGuarded":'Crown Guarded',
 "TFT_Augment_CrownguardSpirit":"Crown's Will",
 "TFT14_Augment_Cutter_Splash":'Cutpurse',
 "TFT14_Augment_Exotech_Cyberdeck":'Cyberdeck',
 "TFT9_Augment_CyberneticBulk2":'Cybernetic Bulk II',
 "TFT6_Augment_CyberneticImplants2":'Cybernetic Implants II',
 "TFT6_Augment_CyberneticUplink2":'Cybernetic Uplink II',
 "TFT14_Augment_Divinicorp_Vertical":'Divine Ascension',
 "TFT14_Augment_DivinicorpCrest":'Divinicorp Crest',
 "TFT14_Augment_Syndicate_DummyWithAGun":'Dummy With A Gun',
 "TFT_Augment_DuoQueue":'Duo Queue',
 "TFT14_Augment_InvokerCrest":'Dynamo Crest',
 "TFT11_Augment_Epoch":'Epoch',
 "TFT11_Augment_EpochPlus":'Epoch+',
 "TFT14_Augment_ExecutionerCrest":'Executioner Crest',
 "TFT14_Augment_ExotechCrest":'Exotech Crest',
 "TFT14_Augment_Marksman_Vertical":'Flatline',
 "TFT_Augment_ForwardThinking":'Forward Thinking',
 "TFT14_Augment_StreetDemon_Freestyling":'Freestyling',
 "TFT_Augment_GlassCannonII":'Glass Cannon II',
 "TFT_Augment_GoldForDummies":'Gold For Dummies',
 "TFT14_Augment_Immortal_Vertical":'Golden Fleece',
 "TFT14_Augment_Immortal_VerticalPlus":'Golden Fleece+',
 "TFT14_Augment_GoldenOxCrest":'Golden Ox Crest',
 "TFT_Augment_Golemify":'Golemify',
 "TFT9_Augment_HealingOrbsII":'Healing Orbs II',
 "TFT_Augment_WealthyRehab2":'Health is Wealth II',
 "TFT10_Augment_HeroicGrabBag":'Heroic Grab Bag',
 "TFT_Augment_HeroicGrabBagPlus":'Heroic Grab Bag+',
 "TFT_Augment_HeroicGrabBagPlusPlus":'Heroic Grab Bag++',
 "TFT_Augment_HighVoltage":'High Voltage',
 "TFT14_Augment_Suits_CorporateCashOut":'Hostile Takeover',
 "TFT14_Augment_Boombots_BigBoom":'Hunter Killer Missile',
 "TFT6_Augment_HyperRoll":'Hustler',
 "TFT10_Augment_InspiringEpitaph":'Inspiring Epitaph',
 "TFT_Augment_InvestmentStrategy1":'Investment Strategy I',
 "TFT_Augment_ItemCollector2":'Item Collector II',
 "TFT14_Augment_Syndicate_KeepYourFriendsClose":'Keep Your Friends Close',
 "TFT7_Augment_LastStand":'Last Stand',
 "TFT14_Augment_Strong_Vertical":'Lethal Rerouting',
 "TFT14_Augment_Suits_Liquidate":'Liquidate',
 "TFT10_Augment_LittleBuddies":'Little Buddies',
 "TFT9_Augment_LongDistanceRelationship2":'Long Distance Pals',
 "TFT_Augment_GuardbreakerSpirit":"Mace's Will",
 "TFT_Augment_MirroredMonetization":'Malicious Monetization',
 "TFT_Augment_Manaflow2":'Manaflow II',
 "TFT14_Augment_MarksmanCrest":'Marksman Crest',
 "TFT14_Augment_Thirsty_Vertical":'Memory Bank',
 "TFT_Augment_Mentorship2":'Mentorship II',
 "TFT_Augment_Moonlight":'Moonlight',
 "TFT_Augment_NoScoutNoPivot":'NO SCOUT NO PIVOT',
 "TFT14_Augment_Cyberboss_HighScore":'New High Score',
 "TFT_Augment_NobleSacrifice":'Noble Sacrifice',
 "TFT9_Augment_NotToday":'Not Today',
 "TFT_Augment_AllForOneII":'One For All II',
 "TFT14_Augment_Supercharge_Vertical":'Overclocked',
 "TFT_Augment_Overheal":'Overheal',
 "TFT_Augment_PairOfFours":'Pair of Fours',
 "TFT9_Augment_PandorasItems2":"Pandora's Items II",
 "TFT9_Augment_LearningFromExperience2":'Patient Study',
 "TFT_Augment_PiercingLotus1":'Piercing Lotus I',
 "TFT_Augment_Pilfer":'Pilfer',
 "TFT14_Augment_Nitro_PolishedChrome":'Polished Chrome',
 "TFT6_Augment_PortableForge":'Portable Forge',
 "TFT14_Augment_AnimaSquad_PowerUp":'Power Leveling',
 "TFT7_Augment_Preparation2":'Preparation II',
 "TFT11_Augment_Prizefighter":'Prizefighter',
 "TFT9_Augment_PumpingUp2":'Pumping Up II',
 "TFT_Augment_Pyromaniac":'Pyromaniac',
 "TFT11_Augment_RainingGold":'Raining Gold',
 "TFT11_Augment_RainingGoldPlus":'Raining Gold+',
 "TFT14_Augment_DuelistCrest":'Rapidfire Crest',
 "TFT14_Augment_Guardian_Vertical":'Reactive Shell',
 "TFT11_Augment_Reinfourcement":'ReinFOURcement',
 "TFT14_Augment_Bruiser_Vertical":'Reinforcing Skeleture',
 "TFT_Augment_Replication":'Replication',
 "TFT6_Augment_SalvageBin":'Salvage Bin',
 "TFT8_Augment_SalvageBinPlus":'Salvage Bin+',
 "TFT_Augment_SatedSpellweaver":'Sated Spellweaver',
 "TFT10_Augment_Scapegoat":'Scapegoat',
 "TFT_Augment_Scavenger":'Scavenger',
 "TFT11_Augment_ScoreboardScrapper":'Scoreboard Scrapper',
 "TFT_Augment_ShopGlitch":'Shop Glitch',
 "TFT11_Augment_Slammin":"Slammin'",
 "TFT11_Augment_Slammin_Plus":"Slammin'+",
 "TFT14_Augment_SlayerCrest":'Slayer Crest',
 "TFT14_Augment_Nitro_SpareParts":'Spare Parts',
 "TFT_Augment_ShojinSpirit":"Spear's Will",
 "TFT14_Augment_Swift_Vertical":'Speed Kills',
 "TFT_Augment_SpiritLink1":'Spirit Link',
 "TFT9_Augment_DravenSpoilsOfWar2":'Spoils of War II',
 "TFT_Augment_StarryNight": 'Starry Night',
 "TFT_Augment_StarryNightPlus": 'Starry Night+',
 "TFT14_Augment_StrategistCrest":'Strategist Crest',
 "TFT9_Augment_SupportCache":'Support Cache',
 "TFT14_Augment_AnimaSquad_SupportSpire": 'Support Spire',
 "TFT14_Augment_MobCrest": 'Syndicate Crest',
 "TFT14_Augment_StreetDemon_TaggingSpree": 'Tagging Spree',
 "TFT9_Augment_Commander_TeamingUp2":'Teaming Up II',
 "TFT14_Augment_TechieCrest":'Techie Crest',
 "TFT14_Augment_GragasCarry":'The Chug Bug',
 "TFT14_Augment_GragasCarryPlus":'The Chug Bug+',
 "TFT_Augment_ThornPlatedArmor":'Thorn-Plated Armor',
 "TFT_Augment_TombRaider1":'Tomb Raider I',
 "TFT_Augment_TowerDefense":'Tower Defense',
 "TFT6_Augment_TradeSector": 'Trade Sector',
 "TFT_Augment_TraitTracker":'Trait Tracker',
 "TFT14_Augment_Supercharge_Splash":'Transference',
 "TFT14_Augment_Armorclad_Splash":'Transistor',
 "TFT14_Augment_Exotech_TrialRun":'Trial Run',
 "TFT_Augment_Trifecta1": 'Trifecta I',
 "TFT_Augment_TwoMuchValue": 'Two Much Value',
 "TFT_Augment_TwoTrick": 'Two Trick',
 "TFT_Augment_Dhampyr":'Vampiric Vitality',
 "TFT14_Augment_VanguardCrest":'Vanguard Crest',
 "TFT11_Augment_WanderingTrainerGold":'Wandering Trainer I',
 "TFT_Augment_Warpath":'Warpath',
 "TFT_Augment_WorthTheWaitGold":'Worth the Wait',
 "TFT_Augment_AnExaltedAdventure":'An Exalted Adventure',
 "TFT_Augment_OopsAllRageblades":'Anger Issues',
 "TFT14_Augment_AnimaSquadCirclet":'Anima Squad Circlet',
 "TFT14_Augment_AnimaSquadCrown":'Anima Squad Crown',
 "TFT14_Augment_BastionCirclet":'Bastion Circlet',
 "TFT14_Augment_BastionCrown":'Bastion Crown',
 "TFT_Augment_BeltOverflow":'Belt Overflow',
 "TFT7_Augment_BirthdayPresents":'Birthday Present',
 "TFT_Augment_BlazingSoul2":'Blazing Soul II',
 "TFT9_Augment_BlindingSpeed":'Blinding Speed',
 "TFT14_Augment_BoomBotsCirclet":'BoomBot Circlet',
 "TFT14_Augment_BoomBotsCrown":'BoomBot Crown',
 "TFT_Augment_BronzeForLife2":'Bronze For Life II',
 "TFT14_Augment_BruiserCirclet":'Bruiser Circlet',
 "TFT14_Augment_BruiserCrown":'Bruiser Crown',
 "TFT11_Augment_Buildabud":'Build a Bud!',
 "TFT_Augment_BulkyBuddies3":'Bulky Buddies III',
 "TFT9_Augment_BuildingACollectionPlusPlus":'Buried Treasures III',
 "TFT_Augment_CalculatedEnhancement":'Calculated Enhancement',
 "TFT11_Augment_Calltochaos":'Call to Chaos',
 "TFT9_Augment_BardPlaybook3":"Caretaker's Chosen",
 "TFT_Augment_Coronation":'Coronation',
 "TFT9_Augment_CyberneticBulk3":'Cybernetic Bulk III',
 "TFT6_Augment_CyberneticImplants3":'Cybernetic Implants III',
 "TFT6_Augment_CyberneticUplink3":'Cybernetic Uplink III',
 "TFT14_Augment_DivinicorpCirclet":'Divinicorp Circlet',
 "TFT14_Augment_DivinicorpCrown":'Divinicorp Crown',
 "TFT_Augment_DualPurpose":'Dual Purpose',
 "TFT14_Augment_DynamoCirclet":'Dynamo Circlet',
 "TFT14_Augment_DynamoCrown":'Dynamo Crown',
 "TFT14_Augment_ExecutionerCirclet":'Executioner Circlet',
 "TFT14_Augment_ExecutionerCrown": 'Executioner Crown',
 "TFT14_Augment_ExotechCirclet":'Exotech Circlet',
 "TFT14_Augment_ExotechCrown":'Exotech Crown',
 "TFT_Augment_ExpectedUnexpectedness":'Expected Unexpectedness',
 "TFT9_Augment_Commander_FinalAscension":'Final Ascension',
 "TFT_Augment_FinalPolish":'Final Polish',
 "TFT_Augment_Flexible":'Flexible',
 "TFT_Augment_FlurryOfBlows":'Flurry of Blows',
 "TFT10_Augment_GoingLong":'Going Long',
 "TFT14_Augment_GoldenOxCirclet":'Golden Ox Circlet',
 "TFT14_Augment_GoldenOxCrown":'Golden Ox Crown',
 "TFT_Augment_GreaterMoonlight":'Greater Moonlight',
 "TFT_Augment_HallOfMirrors":'Hall of Mirrors',
 "TFT_Augment_HardCommit":'Hard Commit',
 "TFT9_Augment_HedgeFund":'Hedge Fund',
 "TFT_Augment_ImTheCarryNow":"I'm the Carry Now",
 "TFT_Augment_RanduinsImmovableObject":'Immovable Object',
 "TFT_Augment_InvestedPlus":'Invested+',
 "TFT_Augment_InvestedPlusPlusv":'Invested++',
 "TFT_Augment_InvestmentStrategy2":'Investment Strategy II',
 "TFT6_Augment_MaxLevel10":'Level Up!',
 "TFT7_Augment_LivingForge":'Living Forge',
 "TFT7_Augment_LuckyGloves":'Lucky Gloves',
 "TFT7_Augment_LuckyGlovesPlus":'Lucky Gloves+',
 "TFT14_Augment_MarksmanCirclet":'Marksman Circlet',
 "TFT14_Augment_MarksmanCrown":'Marksman Crown',
 "TFT_Augment_MaxCap":'Max Cap',
 "TFT_Augment_OneBuffTwoBuff":'One Buff, Two Buff',
 "TFT9_Augment_PandorasRadiantBox":"Pandora's Items III",
 "TFT9_Augment_PhreakyFriday":'Phreaky Friday',
 "TFT9_Augment_PhreakyFridayPlus":'Phreaky Friday +',
 "TFT_Augment_PiercingLotus2":'Piercing Lotus II',
 "TFT_Augment_PrismaticPipeline":'Prismatic Pipeline',
 "TFT6_Augment_GachaAddict":'Prismatic Ticket',
 "TFT9_Augment_PumpingUp3":'Pumping Up III',
 "TFT_Augment_QualityOverQuantity":'Quality Over Quantity',
 "TFT11_Augment_RadiantRefactor":'Radiant Refactor',
 "TFT6_Augment_RadiantRelics":'Radiant Relics',
 "TFT14_Augment_RapidfireCirclet":'Rapidfire Circlet',
 "TFT14_Augment_RapidfireCrown":'Rapidfire Crown',
 "TFT9_Augment_RollTheDice":'Roll The Dice',
 "TFT_Augment_ShimmerscaleEssence":'Shimmerscale Essence',
 "TFT9_Augment_HighEndSector":'Shopping Spree',
 "TFT14_Augment_SlayerCirclet":'Slayer Circlet',
 "TFT14_Augment_SlayerCrown":'Slayer Crown',
 "TFT9_Augment_DravenSpoilsOfWar3":'Spoils of War III',
 "TFT_Augment_Sponging":'Sponging',
 "TFT14_Augment_StrategistCirclet":'Strategist Circlet',
 "TFT14_Augment_StrategistCrown":'Strategist Crown',
 "TFT14_Augment_StreetDemonCirclet":'Street Demon Circlet',
 "TFT14_Augment_StreetDemonCrown":'Street Demon Crown',
 "TFT_Augment_SubscriptionService":'Subscription Service',
 "TFT_Augment_SwordOverflow":'Sword Overflow',
 "TFT14_Augment_SyndicateCirclet":'Syndicate Circlet',
 "TFT14_Augment_SyndicateCrown":'Syndicate Crown',
 "TFT_Augment_TacticiansKitchen":"Tactician's Kitchen",
 "TFT14_Augment_TechieCirclet":'Techie Circlet',
 "TFT14_Augment_TechieCrown":'Techie Crown',
 "TFT9_Augment_TiniestTitan":'Tiniest Titan',
 "TFT9_Augment_TiniestTitanPlus":'Tiniest Titan+',
 "TFT_Augment_TombRaider2":'Tomb Raider II',
 "TFT_Augment_Trifecta2":'Trifecta II',
 "TFT_Augment_UpwardMobility":'Upward Mobility',
 "TFT14_Augment_VanguardCirclet":'Vanguard Circlet',
 "TFT14_Augment_VanguardCrown":'Vanguard Crown',
 "TFT_Augment_Voidborne":'Void Swarm',
 "TFT_Augment_WandOverflow":'Wand Overflow',
 "TFT9_Augment_WanderingTrainer":'Wandering Trainer II',
 "TFT_Augment_WorthTheWaitPrismatic":'Worth the Wait II'
}

#need to add something if there is an open hero slot

@app.route('/decide', methods=['GET'])
def decide():
    board[decision] = "MASK"
    return jsonify({"data": 'ok'}), 200, {'Content-Type': 'application/json'}

@app.route('/items', methods=['POST'])
def items():
    data = request.get_json()['items']
    for i, item in enumerate(data):
        if item == "":
            item = "ITEM_SLOT"
        board[shop_boundary+1+i] = item
    return jsonify({"data": 'ok'}), 200, {'Content-Type': 'application/json'}

@app.route('/augments', methods=['POST'])
def augments():
    data = request.get_json()['augments']
    for i, augment in enumerate(data):
        board[decision+1+i] = augment
    board[decision] = "ACTION_AUGMENT"
    board[decision + 4] = "MASK"
    return jsonify({"data": 'ok'}), 200, {'Content-Type': 'application/json'}

@app.route('/update', methods=['POST'])
def update():
    data_json = request.get_json()
    try:
        data = data_json['data']['info']
    except:
        print(data_json)
        return jsonify({"data": '1'}), 200, {'Content-Type': 'application/json'}
    first_key = next(iter(data))

    # Handle based on first key
    if first_key == 'store':
        shop  = json.loads(data['store']['shop_pieces'])
        for i,slot in enumerate(shop.keys()):
            if shop[slot]['name'] != "Sold":
                board[bench_boundary+i+1] = unit_dict[shop[slot]['name']]
            else:
                board[bench_boundary+i+1] = 'PAD'
    elif first_key == 'me':
        # Do something with player state
        if int(data['me']['gold']) < 2:
            board[reroll] = 'CANT_REROLL'
        else:
            board[reroll] = 'CAN_REROLL'
    elif first_key == 'bench':
        bench = json.loads(data['bench']['bench_pieces'])
        for i,slot in enumerate(bench.keys()):
            board[hero_boundary+i+1] = unit_dict[bench[slot]['name']]
    elif first_key == 'board':
        board_data = json.loads(data['board']['board_pieces'])
        for i,slot in enumerate(board_data.keys()):
            board[i*3+1] = unit_dict[board_data[slot]['name']]
            board[i*3+2] = item_dict[board_data[slot]['item_1']]
            board[i*3+3] = item_dict[board_data[slot]['item_2']]
            board[i*3+4] = item_dict[board_data[slot]['item_3']]
    else:
        pass
    return jsonify({"data": board}), 200, {'Content-Type': 'application/json'}

if __name__ == '__main__':
    app.run(debug=True)